"use client"

export const SEASONS_DATA = [
  {
    id: 1,
    title: "Season 1",
    subtitle: "ORIGIN",
    tagline: "THE SYSTEM WAKES",
    description: "Start your robotics journey. Master the fundamentals with power & circuits, Python, Linux, sensors, motors and more.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/S1-TMgawNmw4PW42rv4YoQ8jhJPuoPjb0.png",
    releaseDate: "Coming Soon",
    episodes: [
      {
        id: 1,
        title: "Episode 1: Getting Started",
        description: "Learn the basics of robotics, set up your environment, and build your first circuit. This foundational episode covers essential concepts you'll use throughout the journey.",
        duration: "45 min",
        videoUrl: "https://youtu.be/T5rmd-vKQeM?si=FFfRVj_tJ-ZlkJK6",
        summary: "In this introductory episode, we cover the fundamentals of robotics including basic electrical concepts, safety practices, and hardware setup. You'll learn how to use Arduino, sensors, and motors effectively.",
        files: [
          { name: "starter_circuit.ino", type: "Code" },
          { name: "components_guide.pdf", type: "Guide" },
          { name: "shopping_list.xlsx", type: "Bill of Materials" },
        ],
        codes: [
          { language: "Arduino", snippet: "void setup() { Serial.begin(9600); pinMode(LED_PIN, OUTPUT); }" },
        ],
      },
      {
        id: 2,
        title: "Episode 2: Arduino Basics",
        description: "Deep dive into Arduino programming. Learn how to write code, debug, and interact with your first sensor.",
        duration: "50 min",
        videoUrl: "https://youtu.be/yqWX86uT5jM?si=iUXKyNpoJE0lIYk2",
        summary: "Explore Arduino fundamentals including setup, loops, digital and analog I/O, and serial communication.",
        files: [],
        codes: [],
      },
      {
        id: 3,
        title: "Episode 3: Sensor Integration",
        description: "Master PID tuning algorithms and implement digital filters on Arduino hardware.",
        duration: "55 min",
        videoUrl: "https://www.youtube.com/watch?v=t3U3x_kUIbc&list=RDMMt3U3x_kUIbc&start_radio=1",
        isFree: true,
        summary: "Learn how to connect and read from various sensors, process data, and make decisions based on sensor inputs.",
        files: [],
        codes: [],
      },
      {
        id: 4,
        title: "Episode 4: Motor Control",
        description: "Control DC motors, servo motors, and stepper motors. Build a simple moving robot.",
        duration: "60 min",
        videoUrl: "https://youtu.be/yqWX86uT5jM?si=iUXKyNpoJE0lIYk2",
        summary: "Master motor control techniques including PWM, direction control, and speed regulation.",
        files: [],
        codes: [],
      },
    ],
  },
  {
    id: 2,
    title: "Season 2",
    subtitle: "CONTROL",
    tagline: "BUILD AND CONTROL SOPHISTICATED ROBOTIC ARMS",
    description: "Build and control sophisticated robotic arms. Learn inverse kinematics, MATLAB, and advanced control systems.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/S2-QmmZlnDwcmtzEALHQbEehK5kvnfbIx.png",
    releaseDate: "Coming Soon",
    episodes: [
      { id: 1, title: "Episode 1: Arm Design", description: "Design your first robotic arm", duration: "45 min", videoUrl: "https://youtu.be/yqWX86uT5jM?si=iUXKyNpoJE0lIYk2", summary: "", files: [], codes: [] },
    ],
  },
  {
    id: 3,
    title: "Season 3",
    subtitle: "AUTONOMY",
    tagline: "AUTONOMOUS ROVER",
    description: "Create intelligent rovers that navigate autonomously. Learn ROS2, pathfinding, and obstacle avoidance.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/S3-dkcfTAzYPs8lhaNyjRDyonuxfNOGQH.png",
    releaseDate: "Coming Soon",
    episodes: [
      { id: 1, title: "Episode 1: Rover Basics", description: "Build your autonomous rover", duration: "45 min", videoUrl: "https://youtu.be/yqWX86uT5jM?si=iUXKyNpoJE0lIYk2", summary: "", files: [], codes: [] },
    ],
  },
  {
    id: 4,
    title: "Season 4",
    subtitle: "EVOLUTION",
    tagline: "QUADRUPED FROM ZERO",
    description: "Engineer a four-legged walking robot from scratch. Learn advanced kinematics and control.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/S4-kHT4MtQZ9WUHGDkrQ8ongThvdIiScx.png",
    releaseDate: "Coming Soon",
    episodes: [
      { id: 1, title: "Episode 1: Quadruped Design", description: "Design a four-legged robot", duration: "45 min", videoUrl: "https://youtu.be/yqWX86uT5jM?si=iUXKyNpoJE0lIYk2", summary: "", files: [], codes: [] },
    ],
  },
  {
    id: 5,
    title: "Season 5",
    subtitle: "DOMINATION",
    tagline: "WORLD MAP ROBOTICS",
    description: "Advanced simulations and real-world applications. Deploy robots globally with NVIDIA integration.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/S5-7V6V5sXMn0k6ncMoo91fe8Ck0CpCpX.png",
    releaseDate: "Coming Soon",
    episodes: [
      { id: 1, title: "Episode 1: Global Deployment", description: "Deploy robots worldwide", duration: "45 min", videoUrl: "https://youtu.be/yqWX86uT5jM?si=iUXKyNpoJE0lIYk2", summary: "", files: [], codes: [] },
    ],
  },
]
